// app/layout.tsx
import './globals.css'; // Your global styles, if any
import { ReactNode } from 'react';

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}

function Header() {
  return (
    <header style={{ padding: '1rem', backgroundColor: '#005C06', color: 'white' }}>
      <nav>
        <ul style={{ display: 'flex', justifyContent: 'space-around' }}>
          <li><a href="/">Home</a></li>
          <li><a href="/sales">Sales</a></li>
          <li><a href="/products">Products</a></li>
          <li><a href="/stocks">Stocks</a></li>
        </ul>
      </nav>
    </header>
  );
}

function Footer() {
  return (
    <footer style={{ padding: '1rem', backgroundColor: '#005C06', color: 'white', marginTop: 'auto' }}>
      <p>&copy; 2024 Bonison</p>
    </footer>
  );
}
